# Site settings
title: Schachfreunde Wedel
description: > # this means to ignore newlines until "baseurl:"
  Schach in Wedel
url: "http://balimonster.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: balimonster
meeting_schedule: Dienstags 19:00 Stadtteilzentrum Mittendrin
paginate: 20
# Build spwd
# ettings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
