# Site settings
title: Arctic Fox
email:
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
url: "http://balimonster.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: balimonster

# Build spwd
# ettings
markdown: kramdown
